export const seedData = {
  projects: [
    {
      id: 'proj_1',
      name: 'Daily AI Shorts',
      description: 'Tech news shorts for social media',
      contentType: 'video',
      defaultAspectRatio: '9:16',
      defaultDuration: 30,
      primaryLanguage: 'English',
      targetPlatforms: ['YouTube Shorts', 'TikTok'],
      tags: ['tech', 'news', 'shorts'],
      createdAt: '2024-01-15T00:00:00.000Z',
      updatedAt: '2024-01-20T00:00:00.000Z',
    },
    {
      id: 'proj_2',
      name: 'Product Demos',
      description: 'AI-generated product showcase videos',
      contentType: 'video',
      defaultAspectRatio: '16:9',
      defaultDuration: 60,
      primaryLanguage: 'English',
      targetPlatforms: ['YouTube Shorts'],
      tags: ['product', 'demo', 'marketing'],
      createdAt: '2024-01-10T00:00:00.000Z',
      updatedAt: '2024-01-18T00:00:00.000Z',
    },
  ],
  templates: [
    {
      id: 'tpl_1',
      name: 'Cinematic Video',
      description: 'Create cinematic videos with AI visuals and audio',
      category: 'Video',
      thumbnail: '',
      tags: ['cinematic', 'film', 'dramatic'],
      nodes: [],
      connections: [],
    },
    {
      id: 'tpl_2',
      name: 'Social Media Shorts',
      description: 'Vertical shorts for TikTok, Reels, and Shorts',
      category: 'Video',
      thumbnail: '',
      tags: ['shorts', 'social', 'viral'],
      nodes: [],
      connections: [],
    },
    {
      id: 'tpl_3',
      name: 'Product Showcase',
      description: 'Highlight your products with AI-generated visuals',
      category: 'Marketing',
      thumbnail: '',
      tags: ['product', 'marketing', 'ecommerce'],
      nodes: [],
      connections: [],
    },
  ],
  generations: [],
  assets: [],
  brandPresets: [
    {
      id: 'brand_1',
      name: 'Minimal Brand',
      fonts: { primary: 'Inter', secondary: 'Inter' },
      colors: { primary: '#1f2937', secondary: '#9ca3af', accent: '#2563eb' },
      captionStyles: {
        fontFamily: 'Inter',
        fontSize: 32,
        textColor: '#ffffff',
        backgroundColor: '#000000',
      },
    },
    {
      id: 'brand_2',
      name: 'Bold Neon',
      fonts: { primary: 'Poppins', secondary: 'Poppins' },
      colors: { primary: '#0f172a', secondary: '#22d3ee', accent: '#f97316' },
      captionStyles: {
        fontFamily: 'Poppins',
        fontSize: 34,
        textColor: '#ffffff',
        backgroundColor: '#0f172a',
      },
    },
  ],
  workflows: [
    {
      id: 'wf_1',
      name: 'Shorts Pipeline',
      projectId: 'proj_1',
      basedOnTemplate: 'tpl_2',
      inputs: [{ name: 'hook', type: 'text', required: true }],
      outputs: [
        { id: 'o1', type: 'final-video', enabled: true },
        { id: 'o2', type: 'thumbnail', enabled: true },
      ],
      watermarkPolicy: true,
      nodes: [],
      connections: [],
      createdAt: '2024-02-01T00:00:00.000Z',
      updatedAt: '2024-02-01T00:00:00.000Z',
    },
  ],
}
